create database zeptodb;


create table zepto(
sku_id serial primary key,
Category varchar(140),
Name varchar(140),
mrp numeric(8,2),
discount_percent  smallint,
availableQuantity smallint,
discountsellingprice int,
weightInGms int,
outofstock boolean,
quantity int
)

select * from zepto

alter table zepto
alter column name type varchar(140)

ALTER SEQUENCE zepto_sku_id_seq RESTART WITH 1;

alter table zepto
alter column discountsellingprice type numeric(8,2)



-- Count the total number of rows in the dataset (3732)
select count(*) as Total_Rows from zepto

-- Display a sample of 10 products from the dataset
select * from zepto
limit 10

-- Check for NULL values in important columns
select * from zepto
where name is null
or
category is null
or
mrp is null
or
discount_percent is null
or
availablequantity is null
or
discountsellingprice is null
or
weightInGms is null
or
outofstock is null
or
quantity is null


-- Find all the unique product categories available in the dataset
select distinct(Category) as category from zepto

-- Compare the number of products that are in stock and out of stock
select outofstock, count(sku_id) as no_of_products
from zepto
group by outofstock


-- Identify products that appear multiple times in the dataset
select name, count(sku_id) as no_of_appearance
from zepto
group by name
having count(sku_id)>1
order by count(sku_id) desc;


-- Data Cleaning

-- Check for products with zero MRP or zero selling price
select * from zepto
where mrp = 0 or discountsellingprice = 0

-- Delete products with zero MRP
delete from zepto
where mrp=0

-- Convert product prices from paise to rupees
update zepto
set mrp= mrp/100.0,
discountsellingprice= discountsellingprice/100.0




-- Business Insights

-- 1) Find the top 5 products offering the highest discount percentage
select distinct name,mrp, discount_percent from zepto
order by discount_percent desc
limit 5

-- 2) Identify high-priced products (MRP > ₹200) that are currently out of stock
select distinct name , mrp, outofstock 
from zepto
where outofstock = 'TRUE' and mrp > 200
ORDER BY mrp desc

-- 3) Calculate the estimated revenue generated by each product category
select Category , sum( discountsellingprice* quantity) as total_revenue
from zepto
group by Category
order by  total_revenue desc


-- 4) Find products with an MRP above ₹500 and a discount percentage below 10%
select distinct name, mrp ,discount_percent from zepto
where mrp > 500 and discount_percent < 10
order by mrp desc

-- 5) Identify the top 5 categories offering the highest average discount percentage

-- Method 1: Using GROUP BY and LIMIT
select Category , round( avg(discount_percent),0) as average from zepto
group by Category
order by average desc
limit 5

-- Method 2: Using DENSE_RANK() to rank categories by average discount
with top5 as (
select Category, round( avg(discount_percent),0) as average,
dense_rank() over(order by avg(discount_percent) desc ) as rnk
from zepto
group by Category
)
select * from top5
where rnk < 5

-- 6) Calculate the price per gram for products weighing more than 500g and identify the best value products
select distinct name, discountsellingprice, weightInGms,
round(discountsellingprice/weightInGms,0) as price_per_gram 
from zepto
where weightInGms > 500
order by price_per_gram desc

-- 7) Classify products into Bulk, High, and Medium categories based on their weight
select distinct name, weightInGms,
case when weightInGms > 2000 then 'Bulk'
when weightInGms > 1000 then 'High'
else 'Medium'
end as categories
from zepto

-- 8) Calculate the total inventory weight available in each product category
select Category , sum(weightInGms*quantity) as inventory_weight
from zepto
group by Category 
order by inventory_weight